baseURL                 = "https://burgundyshark.github.io/sarahrobin.net/"
languageCode            = "en-us"
title                   = "Sarah Robin - Development & Design"
theme                   = "Sam"
pygmentsStyle           = "manni"                      # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics       = "xxx"                        # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    portfolioFolder     = "images/"                     # Where you've put your images, after "/content/portfolio/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = ""

# Metadata
    # Max 160 characters show in search results
    description         = "Sarah Robin is a freelance web developer, designer, and artist"            
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links


[[params.mainMenu]]
    link = "/portfolio"
    text = "work"

[[params.mainMenu]]
    link = "/posts"
    text = "writing"

[[params.mainMenu]]
    link = "/about"
    text = "about"